version: '2'
services:
  scheduler:
    image: ajacques/rancher-webhook:latest
    environment:
      REDIS_URI: redis:6379/resque
    cap_drop:
    - ALL
    links:
    - Redis:redis
    command:
    - rake
    - resque:scheduler
  Agent:
    image: ajacques/rancher-webhook:latest
    environment:
      REDIS_URI: redis:6379/resque
    cap_drop:
    - ALL
    links:
    - Redis:redis
    labels:
      io.rancher.container.pull_image: always
  Redis:
    cap_add:
    - CHOWN
    - SETGID
    - SETUID
    cap_drop:
    - ALL
    image: redis:3.2.6-alpine
    labels:
      io.rancher.sidekicks: Data
    volumes_from:
    - Data
  Data:
    image: busybox:latest
    mem_limit: 4194304
    cap_drop:
    - ALL
    network_mode: none
    volumes:
    - /data
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.pull_image: always
  worker:
    cap_drop:
    - ALL
    command:
    - rake
    - resque:work
    environment:
      QUEUE: '*'
      RANCHER_URI: ${RANCHER_URI}
      REDIS_URI: redis:6379/resque
    image: ajacques/rancher-webhook:latest
    labels:
      io.rancher.container.create_agent: true
      io.rancher.container.agent.role: environment
    links:
    - Redis:redis
